### ISSUE TITLE
Incompatibility with Laravel 9

### ISSUE THREAD

**Issue by l-alexandrov** [Daursu/laravel-zero-downtime-migration#24]
Laravel 9 [requires an incompatible version](https://github.com/laravel/framework/blob/9.x/composer.json#L41) of `symfony/process`.

Your product [require](https://github.com/Daursu/laravel-zero-downtime-migration/blob/0.9.0/composer.json#L9) "^3.3|^4.0|^5.0" of the package, while Laravel require "^6.0"

**Comment by Daursu** [comment]
Thanks for reporting this. I've fixed it in #25
