### ISSUE TITLE
 Unsupported driver [pt-online-schema-change]

### ISSUE THREAD

**Issue by M0H3N** [Daursu/laravel-zero-downtime-migration#29]
Hi 

I got this error :  Unsupported driver [pt-online-schema-change]. 

could you please help me ?

**Comment by Daursu** [comment]
Can you check to see if you registered the service provider in your `config/app.php` file like so

```php
'providers' => [
  ...
  Daursu\ZeroDowntimeMigration\ServiceProvider::class,
],
```

**Comment by niftyhack** [comment]
Hi @M0H3N 

I just found this repo while searching for a solution to our problem: Running migrations with Laravel on a Percona-Xtra-DB-Cluster.

Are you still using this package or have you found another way for efficient database migrations with Laravel?
