### ISSUE TITLE
--pretend also executes the query

### ISSUE THREAD

**Issue by weerdm** [Daursu/laravel-zero-downtime-migration#4]
Hi! Thank you for this great package. 

Just one side note: when using `php artisan migrate --pretend`, the command `pt-online-schema-change` still executes. Might be unexpected behaviour. Would be nice if `pt-online-schema-change` was executed with the `--dry-run` property :)

**Comment by Daursu** [comment]
Thanks, will release an update.

**Comment by Daursu** [comment]
@weerdm this has been fixed in the latest release 0.3.0 (#5)
