### ISSUE TITLE
Is there an option here to shrink the table?

### ISSUE THREAD

**Issue by phpguru** [Daursu/laravel-zero-downtime-migration#42]
If you're reading this you probably know you can't reclaim disk space by deleting rows, only by making a new table with less data in it. We have 5 tables > 150M rows going back to 2015 and don't need it all. Wondering if there is a way with this library to only move _a portion of the data_ to the new table, and into the same schema. That is to say, it is not technically a migration, but still needs a pattern like online-schema-change to create new table, copy latest 2 years of data for example, then drop and rename. TIA!

**Comment by phpguru** [comment]
> Change sakila.actor to InnoDB, effectively performing OPTIMIZE TABLE in a non-blocking fashion because it is already an InnoDB table:
> 
> ```
> pt-online-schema-change --alter "ENGINE=InnoDB" D=sakila,t=actor
> ```

How would the migration look for this type of change? Incidentally I only can find a Bug and a Blueprint (suggestion for a new feature) for adding WHERE clause support for Percona Tools.

Refs: 
1. https://bugs.launchpad.net/percona-toolkit/+bug/1036311
2. https://blueprints.launchpad.net/percona-toolkit/+spec/pt-online-schema-change-where

**Comment by Daursu** [comment]
I couldn't see an option of dropping certain rows using Percona, however one solution you can try is:
1. Backup existing table
2. Delete unnecessary data from your current table 
3. Perform a migration of your table using Percona migration tool

The new table should be smaller and only contain the new records you need. The drawback with this approach is rolling back in case of issues. You'll have to manually re-insert the deleted rows from the backup in step 1.

**Comment by phpguru** [comment]
Thanks for confirming @Daursu - that's kind of what I figured out after several hours of searching. It seems that pt-online-schema-change only ever had a [bug](https://perconadev.atlassian.net/browse/PT-1012) and a [proposal](https://blueprints.launchpad.net/percona-toolkit/+spec/pt-osc-where) to support `--where=` option. The bug is marked as Done but Invalid, so it's a bit tricky to find sort out the status of this feature.
